<option value="Science Fiction">Science Fiction</option>
<option value="Mystery">Mystery</option>
<option value="Romance">Romance</option>
<option value="Fantasy">Fantasy</option>
<option value="Thriller">Thriller</option>
<option value="Historical Fiction">Historical Fiction</option>
<option value="Dystopian">Dystopian</option>
<option value="Biography">Biography</option>
<option value="Adventure">Adventure</option>
<option value="Non-Fiction">Non-Fiction</option>
<option value="Horror">Horror</option>
<option value="Comedy">Comedy</option>
<option value="Self-Help">Self-Help</option>
<option value="Poetry">Poetry</option>
<option value="Islamic">Islamic</option>
<option value="Science">Science</option>
<option value="Philosophy">Philosophy</option>
<option value="Financial">Financial</option>